require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '10.0'

target 'dc0925' do
  use_unimodules!
  config = use_native_modules!
  pod 'EXDevMenuInterface', path: '../node_modules/expo-dev-menu-interface'
  pod 'EXDevMenu', path: '../node_modules/expo-dev-menu', :configurations => :debug

  use_react_native!(:path => config["reactNativePath"])

  target 'dc0925Tests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'dc0925-tvOS' do
  # Pods for dc0925-tvOS

  target 'dc0925-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
